minimum_pre_commit_version: 3.3.3

repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.13"
    hooks:
      - id: ruff
        name: ruff-lint
        entry: ruff check --fix
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.10.0"
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: mypy
  #       args: ["--exclude", "scripts/$"]
  #       language: python
  #       types_or: [python, pyi]
  #       require_serial: true
  #       additional_dependencies: [
  #         "pandas-stubs",
  #         "types-PyYAML",
  #         "types-python-dateutil"
  #       ]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=4000']
      - id: debug-statements
      - id: detect-private-key
      - id: check-toml
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=115, --wrap-descriptions=120]
