[project]
name = "flood-detection-dl"
version = "0.1.0"
description = "Flood Detection Core"
readme = "README.md"
authors = [
    { name = "Truong Hoang", email = "truonghm.work@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "pydantic>=2.11.7",
    "rasterio>=1.4.3",
    "scipy>=1.16.0",
    "seaborn>=0.13.2",
    "setuptools>=78.1.0",
    "earthengine-api>=1.5.9",
    "geemap>=0.35.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
