pretrain:
  num_patches: 300
  num_temporal_length: 4
  patch_size: 16
  input_channels: 2
  hidden_channels: 64
  latent_dim: 128
  learning_rate: 0.001
  max_epochs: 50
  scheduler_patience: 5
  scheduler_factor: 0.1
  scheduler_min_lr: 0.00001
  early_stopping_patience: 10
  batch_size: 128
  vv_clipped_range: [-20.4, -2.3]
  vh_clipped_range: [-30.8, -7.0]

site_specific:
  num_temporal_length: 4
  patch_size: 16
  patch_stride: 2
  input_channels: 2
  hidden_channels: 64
  latent_dim: 128
  learning_rate: 0.0001
  max_epochs: 50
  scheduler_patience: 3
  scheduler_factor: 0.1
  scheduler_min_lr: 0.000001
  batch_size: 32
  early_stopping_patience: 8
  alpha: 0.01
  beta: 0.7
  max_patches_per_pair: all
  positive_pair_ratio: 0.5
  vv_clipped_range: [-20.4, -2.3]
  vh_clipped_range: [-30.8, -7.0]

inference:
  num_temporal_length: 4
  patch_size: 16
  patch_stride: 1
  pad_size: 8
  batch_size: 512
  threshold: 0.5
  pre_flood_vv_clipped_range: [-20.4, -2.3]
  pre_flood_vh_clipped_range: [-30.8, -7.0]
  post_flood_vv_clipped_range: [-20.4, -2.3]
  post_flood_vh_clipped_range: [-30.8, -7.0]
  normalize_site_name: false

augmentation:
  geometric:
    left_right: 0.5
    up_down: 0.2
    rotate: [-90, 90]
  non_geometric:
    gaussian_blur: 0.3
    gamma_contrast_prob: 0.5
    gamma_contrast: [0.25, 2.0]
